import { motion } from "framer-motion";
import { useState } from 'react';
import Head from 'next/head';

export default function Home() {
  const [td, setTD] = useState("12%");
  const [cdb, setCDB] = useState("12%");
  const [cdi, setCDI] = useState("12%");
  const [lci, setLCI] = useState("12%");
  const [lc, setLC] = useState("12%");
  const [db, setDB] = useState("12%");
  const [pp, setPP] = useState("12%");

  async function Update(value) {
    if(value.trim() === "" || value == null || value.length > 23) {
    } else {
      setTD(value);
      setCDB(value);
      setCDI(value);
      setLCI(value);
      setLC(value);
      setDB(value);
      setPP(value);
    }
  }

  return (
    <>
      <Head>
        <title>Apliquest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
        <section className="min-h-screen flex flex-col items-center text-center py-20">
          <div className="w-full max-w-xs rounded-xl mb-10">
            <input placeholder='R$ 0,00' maxLength='10' className='ring-0 outline-0 text-center text-xl text-teal-400 underline decoration-dotted' onChange={e => Update(e.target.value )}/>
          </div>

          <div className="w-full max-w-xs rounded-xl bg-neutral-100 mb-3 p-2 shadow-md">
            <h1>TESOURO DIRETO</h1>
            <h1 className="text-teal-400">{td}</h1>
          </div>

          <div className="w-full max-w-xs rounded-xl bg-neutral-100 mb-3 p-2 shadow-md">
            <h1>CDB</h1>
            <h1 className="text-teal-400">{cdb}</h1>
          </div>

          <div className="w-full max-w-xs rounded-xl bg-neutral-100 mb-3 p-2 shadow-md">
            <h1>CDI</h1>
            <h1 className="text-teal-400">{cdi}</h1>
          </div>

          <div className="w-full max-w-xs rounded-xl bg-neutral-100 mb-3 p-2 shadow-md">
            <h1>LCI/LCA</h1>
            <h1 className="text-teal-400">{lci}</h1>
          </div>

          <div className="w-full max-w-xs rounded-xl bg-neutral-100 mb-3 p-2 shadow-md">
            <h1>LC</h1>
            <h1 className="text-teal-400">{lc}</h1>
          </div>

          <div className="w-full max-w-xs rounded-xl bg-neutral-100 mb-3 p-2 shadow-md">
            <h1>DEBÊNTURES</h1>
            <h1 className="text-teal-400">{db}</h1>
          </div>

          <div className="w-full max-w-xs rounded-xl bg-neutral-100 shadow-md mb-10 p-2 ">
            <h1>POUPANÇA</h1>
            <h1 className="text-teal-400">{pp}</h1>
          </div>

          <div className="w-full mb-10">
            <h1>Qual investimento é o mais adequado para mim?</h1>
            <h1 className="text-teal-400 cursor-pointer text-xl mt-1">REALIZAR TESTE DE PERFIL</h1>
          </div>

          <div className="w-full max-w-xl bg-neutral-100 rounded-xl bg-neutral-100 shadow-md p-5 text-left">
            <h1 className="mb-5">O que é a Taxa Selic?</h1>
            <p className="text-neutral-400">​A Selic é a taxa básica de juros da economia. É o principal instrumento de política monetária utilizado pelo Banco Central (BC) para controlar a inflação. Ela influencia todas as taxas de juros do país, como as taxas de juros dos empréstimos, dos financiamentos e das aplicações financeiras.</p>
          </div>
        </section>
      </motion.div>
    </>
  )
}
